name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    name: Node ${{ matrix.node-version }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Ensure docs directory
      run: mkdir resources/docs

    - name: Create .env file
      run: cp .env.example .env

    - name: Clone docs repository
      uses: actions/checkout@v2
      with:
        repository: supercharge/docs
        path: resources/docs/2.x
        ref: 2.x

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests
      run: npm test
      env:
        CI: true
